# Generated by Django 4.2.7 on 2023-12-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='keepactive',
        ),
    ]
