# Generated by Django 5.0 on 2023-12-10 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='timestamp_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='timestamp_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
