# Generated by Django 5.0 on 2023-12-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_useractivity_duration_useractivity_timestamp_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='timestamp_start',
        ),
    ]
